version: '3.8'

services:
  app:
    build:
      context: .
    image: laravel-app
    container_name: laravel-app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - laravel-storage:/var/www/storage
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: nginx-laravel
    restart: always
    ports:
      - "1009:80"
    volumes:
      - ./:/var/www
      - laravel-storage:/var/www/storage
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: postgres-laravel
    restart: always
    ports:
      - "1007:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - laravel

volumes:
  dbdata:
  laravel-storage:

networks:
  laravel:
    driver: bridge
